#!/usr/bin/env bash
# Regenerate internal/uapi/testdata/linux-le-fixtures.txt from a Linux UAPI
# header, and fail if scripts/uapi-fixtures.c misses any macro or struct member
# the header defines (so a header bump cannot silently go unmodelled).
#
#   scripts/uapi-fixtures.sh INCLUDE_DIR > internal/uapi/testdata/linux-le-fixtures.txt
#
# INCLUDE_DIR must contain linux/ublk_cmd.h and linux/fs.h (v6.17+ for LBMD_PI_*).
# Needs a C compiler and awk; runs no kernel code.
set -euo pipefail

inc=${1:?usage: $0 INCLUDE_DIR}
hdr=$inc/linux/ublk_cmd.h
here=$(cd "$(dirname "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -f "$tmp"/fixtures "$tmp"/out; rmdir "$tmp"' EXIT

${CC:-cc} -std=gnu11 -Wall -Werror -I"$inc" "$here/uapi-fixtures.c" -o "$tmp/fixtures"
"$tmp/fixtures" > "$tmp/out"

missing=0
# Every object-like macro except the include guard.
for name in $(sed -nE 's/^[[:space:]]*#[[:space:]]*define[[:space:]]+([A-Za-z_0-9]+)([[:space:]]|$).*/\1/p' "$hdr"); do
	[ "$name" = USER_BLK_DRV_CMD_INC_H ] && continue
	if ! grep -q "^const $name " "$tmp/out"; then
		echo "uapi-fixtures.c does not emit macro $name" >&2
		missing=1
	fi
done
# Every member of every top-level struct, union alternatives included.
members=$(awk '
	/^struct [a-z_0-9]+[ \t]*\{/ { s = $2; depth = 0; print "sizeof " s }
	s != "" {
		if (match($0, /^[ \t]*(__u8|__u16|__u32|__u64|__s16|__s32|__s64|struct[ \t]+[a-z_0-9]+)[ \t]+[a-z_0-9]+(\[[0-9]+\])?;/)) {
			line = substr($0, RSTART, RLENGTH)
			sub(/(\[[0-9]+\])?;$/, "", line)
			n = split(line, w, /[ \t]+/)
			print "field " s "." w[n]
		}
		depth += gsub(/\{/, "{") - gsub(/\}/, "}")
		if (depth == 0) s = ""
	}' "$hdr")
while read -r kind name; do
	if ! grep -q "^$kind $name " "$tmp/out"; then
		echo "uapi-fixtures.c does not emit $kind $name" >&2
		missing=1
	fi
done <<< "$members"
[ "$missing" = 0 ] || exit 1

echo "# Generated by scripts/uapi-fixtures.sh; do not edit."
echo "# ublk_cmd.h sha256 $(sha256sum "$hdr" | cut -d' ' -f1), $(uname -m), $(${CC:-cc} --version | head -1)"
cat "$tmp/out"
